# Generated by Django 3.2.4 on 2021-07-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsnaaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='editeur',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='reference',
        ),
        migrations.AddField(
            model_name='documents',
            name='language',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='mot_cle',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='pays',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='strategie_national',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='type_de_doc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
