# Generated by Django 3.2.4 on 2021-06-28 10:08

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dsnaaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='dateCreation',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 6, 28, 11, 8, 56, 993820)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='dateUpdate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 6, 28, 11, 8, 56, 993820)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='autheur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsnaaapp.manager'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
