# Generated by Django 3.2.4 on 2021-08-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsnaaapp', '0002_auto_20210813_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='titre',
            new_name='title',
        ),
    ]
