# Generated by Django 3.2.4 on 2021-07-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsnaaapp', '0002_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='lieu',
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
