# Generated by Django 3.2.4 on 2021-06-28 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dsnaaapp', '0002_auto_20210628_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='autheur',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='dateCreation',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='dateUpdate',
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='date_addition',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='intro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
