# Generated by Django 3.2.4 on 2021-07-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsnaaapp', '0003_alter_documents_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='language',
            field=models.CharField(choices=[('1', 'Fr'), ('2', 'En'), ('3', 'Ar')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='type_de_doc',
            field=models.CharField(choices=[('1', 'PDF'), ('2', 'TXT')], max_length=50, null=True),
        ),
    ]
