# Generated by Django 3.2.4 on 2021-08-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsnaaapp', '0003_rename_titre_image_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='titre',
        ),
    ]
