# Generated by Django 3.2.4 on 2021-06-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsnaaapp', '0003_auto_20210628_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='owner',
            new_name='autheur',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='date_addition',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='intro',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField(max_length=255)),
                ('autheur', models.TextField(max_length=50)),
                ('organization', models.TextField(max_length=100)),
                ('date_publication', models.DateField()),
                ('fichier', models.FileField(upload_to='')),
                ('reference', models.TextField(max_length=50)),
                ('editeur', models.TextField(max_length=50)),
                ('lien', models.TextField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('library', models.ManyToManyField(to='dsnaaapp.Library')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dsnaaapp.category'),
        ),
    ]
