# Generated by Django 3.2.4 on 2021-07-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsnaaapp', '0004_alter_event_date_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event',
            field=models.DateField(),
        ),
    ]
