# Generated by Django 3.2.4 on 2021-07-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsnaaapp', '0004_auto_20210726_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='titre',
            field=models.CharField(max_length=20, unique=True, verbose_name='Titre de document'),
        ),
    ]
