# Generated by Django 3.2.4 on 2021-07-18 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsnaaapp', '0005_alter_event_date_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.AddField(
            model_name='album',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsnaaapp.mediacategory'),
        ),
        migrations.AddField(
            model_name='image',
            name='album',
            field=models.ManyToManyField(to='dsnaaapp.Album'),
        ),
    ]
